// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtZ95HsqxXWmwX65sHFPnNBefl9f4r_Fs',
    appId: '1:427037363194:web:eee4ef4b2186b71c5fb243',
    messagingSenderId: '427037363194',
    projectId: 'gluboom-3b564',
    authDomain: 'gluboom-3b564.firebaseapp.com',
    storageBucket: 'gluboom-3b564.firebasestorage.app',
    measurementId: 'G-D254XSNRPM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5Mlhr1GSW9bKmRfQ4S_z-qulcLkzr_IQ',
    appId: '1:427037363194:android:b0e169bfb9bbb33c5fb243',
    messagingSenderId: '427037363194',
    projectId: 'gluboom-3b564',
    storageBucket: 'gluboom-3b564.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1cjgdsA2c_9UmT2rEeN-xgbfFqkOqZkQ',
    appId: '1:427037363194:ios:088ce3ff04ff78965fb243',
    messagingSenderId: '427037363194',
    projectId: 'gluboom-3b564',
    storageBucket: 'gluboom-3b564.firebasestorage.app',
    androidClientId: '427037363194-efa1dciqb87b6p71urt0mtj1d3arnk6s.apps.googleusercontent.com',
    iosClientId: '427037363194-0o0671nc7dhpjqslspo3c9kq5i0ho40o.apps.googleusercontent.com',
    iosBundleId: 'com.example.gluboom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1cjgdsA2c_9UmT2rEeN-xgbfFqkOqZkQ',
    appId: '1:427037363194:ios:088ce3ff04ff78965fb243',
    messagingSenderId: '427037363194',
    projectId: 'gluboom-3b564',
    storageBucket: 'gluboom-3b564.firebasestorage.app',
    androidClientId: '427037363194-efa1dciqb87b6p71urt0mtj1d3arnk6s.apps.googleusercontent.com',
    iosClientId: '427037363194-0o0671nc7dhpjqslspo3c9kq5i0ho40o.apps.googleusercontent.com',
    iosBundleId: 'com.example.gluboom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtZ95HsqxXWmwX65sHFPnNBefl9f4r_Fs',
    appId: '1:427037363194:web:8db388f7f55d8f845fb243',
    messagingSenderId: '427037363194',
    projectId: 'gluboom-3b564',
    authDomain: 'gluboom-3b564.firebaseapp.com',
    storageBucket: 'gluboom-3b564.firebasestorage.app',
    measurementId: 'G-T4N44F005S',
  );

}